# Generated by Django 5.0.2 on 2024-02-21 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('ML', 'Watch'), ('SM', 'Smartphone'), ('OTH', 'Other')], max_length=3)),
                ('company', models.CharField(max_length=60)),
                ('owner', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=100)),
                ('os', models.CharField(blank=True, max_length=30)),
                ('description', models.TextField(default='5G-Smartphone')),
                ('selling_price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('image', models.ImageField(upload_to='product')),
            ],
        ),
    ]
