# Generated by Django 5.0.2 on 2024-02-22 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_product_delete_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('ML', 'Smartwatch'), ('SM', 'Smartphone'), ('OTH', 'Other')], max_length=3),
        ),
    ]
