# Generated by Django 5.0.2 on 2024-02-22 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('WT', 'Smartwatch'), ('SM', 'Smartphone'), ('OTH', 'Other')], max_length=3),
        ),
    ]
